# Generated by Django 4.2.1 on 2023-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="order",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
